# 2D Array

In [5]:
w, h = 6, 6;
Matrix = [[0 for x in range(w)] for y in range(h)] 

In [6]:
Matrix

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [7]:
import numpy
numpy.zeros((5, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
import numpy as np
  
# 1st argument --> numbers ranging from 0 to 9, 
# 2nd argument, row = 2, col = 3
array = np.random.randint(10, size=(6, 6))
print(array)

[[1 3 8 5 7 3]
 [1 6 8 1 7 7]
 [4 0 5 5 8 2]
 [5 3 3 9 0 1]
 [6 4 1 1 2 0]
 [6 4 2 9 7 1]]


In [50]:
arr = np.random.randint(10, size=(6, 6))
arr

array([[4, 7, 0, 6, 0, 2],
       [6, 2, 6, 5, 7, 2],
       [2, 5, 0, 5, 5, 0],
       [2, 1, 4, 4, 0, 5],
       [5, 4, 9, 1, 8, 5],
       [0, 0, 5, 4, 7, 0]])

In [51]:
for i in range(len(arr)):
    print(arr[i]) # prints row by row 
    print("break")
  

[4 7 0 6 0 2]
break
[6 2 6 5 7 2]
break
[2 5 0 5 5 0]
break
[2 1 4 4 0 5]
break
[5 4 9 1 8 5]
break
[0 0 5 4 7 0]
break


In [52]:
arr

array([[4, 7, 0, 6, 0, 2],
       [6, 2, 6, 5, 7, 2],
       [2, 5, 0, 5, 5, 0],
       [2, 1, 4, 4, 0, 5],
       [5, 4, 9, 1, 8, 5],
       [0, 0, 5, 4, 7, 0]])

In [53]:
for i in range(len(arr)):
    for j in range(len(arr)): # if you reverse 
        #print(arr[j][i])  
        print(arr[i][j])# this gives yoou printing each column by each row 


4
7
0
6
0
2
6
2
6
5
7
2
2
5
0
5
5
0
2
1
4
4
0
5
5
4
9
1
8
5
0
0
5
4
7
0


In [54]:
arr

array([[4, 7, 0, 6, 0, 2],
       [6, 2, 6, 5, 7, 2],
       [2, 5, 0, 5, 5, 0],
       [2, 1, 4, 4, 0, 5],
       [5, 4, 9, 1, 8, 5],
       [0, 0, 5, 4, 7, 0]])

In [55]:
for i in range(len(arr)):
    for j in range(len(arr)): # if you reverse 
        print(arr[j][i])  # this gives you printing each row by each column 
        #print(arr[i][j])# 


4
6
2
2
5
0
7
2
5
1
4
0
0
6
0
4
9
5
6
5
5
4
1
4
0
7
5
0
8
7
2
2
0
5
5
0


# Hour Glass Sum Problem

In [58]:
arr

array([[4, 7, 0, 6, 0, 2],
       [6, 2, 6, 5, 7, 2],
       [2, 5, 0, 5, 5, 0],
       [2, 1, 4, 4, 0, 5],
       [5, 4, 9, 1, 8, 5],
       [0, 0, 5, 4, 7, 0]])

In [68]:
# This is how you get hour glass shape..
for i in range(len(arr)-2):
    for j in range(len(arr)-2):
        print(arr[i][j])
        print(arr[i][j+1])
        print(arr[i][j+2])
        print(arr[i+1][j+1])
        print(arr[i+2][j])
        print(arr[i+2][j+1])
        print(arr[i+2][j+2])

        print("break")

4
7
0
2
2
5
0
break
7
0
6
6
5
0
5
break
0
6
0
5
0
5
5
break
6
0
2
7
5
5
0
break
6
2
6
5
2
1
4
break
2
6
5
0
1
4
4
break
6
5
7
5
4
4
0
break
5
7
2
5
4
0
5
break
2
5
0
1
5
4
9
break
5
0
5
4
4
9
1
break
0
5
5
4
9
1
8
break
5
5
0
0
1
8
5
break
2
1
4
4
0
0
5
break
1
4
4
9
0
5
4
break
4
4
0
1
5
4
7
break
4
0
5
8
4
7
0
break


In [70]:
# Now add them all up individually and get this

for i in range(len(arr)-2):
    for j in range(len(arr)-2):
        print(arr[i][j]+arr[i][j+1]+arr[i][j+2]+arr[i+1][j+1]+arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2])
        
#print(max(sum))

20
29
21
25
26
22
31
28
26
28
32
24
16
27
25
28


In [72]:
# Now put it into a sum variable 
sum = []

for i in range(len(arr)-2):
    for j in range(len(arr)-2):
        sum.append(arr[i][j]+arr[i][j+1]+arr[i][j+2]+arr[i+1][j+1]+arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2])
        
print(sum)
print(max(sum))

[20, 29, 21, 25, 26, 22, 31, 28, 26, 28, 32, 24, 16, 27, 25, 28]
32
